### ISSUE TITLE
Request: disable textarea resize

### ISSUE THREAD

**Issue by brauliobolano** [cabrera-carlos/caribetaxsolutions#2]
In the application, we have a **textarea** input field for **comments**. Currently, users can resize this **textarea**. I recommend disabling this feature to maintain the layout consistency of our application.

**Expected Behavior**
The **textarea** should not be resizable. Its size should remain consistent regardless of user interaction.

**Current Behavior**
Currently, users can resize the **textarea**, which can lead to inconsistencies in our application's layout.

**Steps to Reproduce**
Navigate to the page with the **textarea**.
Click and drag the bottom-right corner of the **textarea**.
Observe that the **textarea** can be resized.
Possible Solution
We can disable the resize feature by applying resize: none; in the CSS for the **textarea**.

**Context**
This issue is important to maintain the layout consistency of our application. It will improve the user experience by preventing unexpected layout changes.

**Comment by cabrera-carlos** [comment]
Appreciate the attention to detail.
