### ISSUE TITLE
Add multi-language support

### ISSUE THREAD

**Issue by cabrera-carlos** [cabrera-carlos/caribetaxsolutions#4]
This feature should include:
- Automatic language detection: The application now automatically detects the browser's language and adjusts the display language accordingly.
- Support for language variations: The application supports all variations of English and Spanish as provided by the browser.
- Default language: In cases where the browser's language is neither English nor Spanish or when the language cannot be detected, the application defaults to Spanish.

**Comment by brauliobolano** [comment]
Working on this issue wile waiting for logo feedback

**Comment by cabrera-carlos** [comment]
WIP in #2
